<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260215165009 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE worker (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, short_name VARCHAR(50) NOT NULL, access_token VARCHAR(255) DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE task_instance ADD worker_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE task_instance ADD CONSTRAINT FK_2F05B926B20BA36 FOREIGN KEY (worker_id) REFERENCES worker (id)');
        $this->addSql('CREATE INDEX IDX_2F05B926B20BA36 ON task_instance (worker_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE worker');
        $this->addSql('ALTER TABLE task_instance DROP CONSTRAINT FK_2F05B926B20BA36');
        $this->addSql('DROP INDEX IDX_2F05B926B20BA36');
        $this->addSql('ALTER TABLE task_instance DROP worker_id');
    }
}
