<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260215152500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_type VARCHAR(255) NOT NULL, entity_id VARCHAR(255) NOT NULL, event_type VARCHAR(255) NOT NULL, payload JSONB NOT NULL, actor_type VARCHAR(50) NOT NULL, actor_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_log_created_at ON audit_log (created_at)');
        $this->addSql('CREATE INDEX idx_audit_log_entity_type ON audit_log (entity_type)');
        $this->addSql('CREATE TABLE production_week (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, week_number INT NOT NULL, status VARCHAR(20) NOT NULL, opened_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_production_week_year_week ON production_week (year, week_number)');
        $this->addSql('CREATE TABLE task_instance (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_snapshot VARCHAR(255) NOT NULL, points_snapshot INT NOT NULL, priority_snapshot VARCHAR(20) NOT NULL, weekday_snapshot INT NOT NULL, status VARCHAR(20) NOT NULL, done_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, week_id BIGINT NOT NULL, template_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F05B925DA0FB8 ON task_instance (template_id)');
        $this->addSql('CREATE INDEX idx_task_instance_week ON task_instance (week_id)');
        $this->addSql('CREATE INDEX idx_task_instance_status ON task_instance (status)');
        $this->addSql('CREATE TABLE task_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, points INT NOT NULL, priority VARCHAR(20) NOT NULL, weekday INT NOT NULL, recurring BOOLEAN NOT NULL, category VARCHAR(50) DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_task_template_recurring_active ON task_template (recurring, active)');
        $this->addSql('ALTER TABLE task_instance ADD CONSTRAINT FK_2F05B92C86F3B2F FOREIGN KEY (week_id) REFERENCES production_week (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_instance ADD CONSTRAINT FK_2F05B925DA0FB8 FOREIGN KEY (template_id) REFERENCES task_template (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE task_instance DROP CONSTRAINT FK_2F05B92C86F3B2F');
        $this->addSql('ALTER TABLE task_instance DROP CONSTRAINT FK_2F05B925DA0FB8');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE production_week');
        $this->addSql('DROP TABLE task_instance');
        $this->addSql('DROP TABLE task_template');
    }
}
