<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260216151959 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE incident (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, status VARCHAR(50) NOT NULL, priority VARCHAR(50) NOT NULL, reported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, handled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, admin_comment TEXT DEFAULT NULL, reported_by_id INT NOT NULL, handled_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3D03A11A71CE806 ON incident (reported_by_id)');
        $this->addSql('CREATE INDEX IDX_3D03A11AFE65AF40 ON incident (handled_by_id)');
        $this->addSql('CREATE TABLE welfare_current_stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(50) NOT NULL, amount INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AAD0E4864C19C1 ON welfare_current_stock (category)');
        $this->addSql('CREATE TABLE welfare_stock_change (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(50) NOT NULL, delta INT NOT NULL, reason VARCHAR(50) NOT NULL, note TEXT DEFAULT NULL, previous_amount INT NOT NULL, new_amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, worker_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B565BE0E6B20BA36 ON welfare_stock_change (worker_id)');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11A71CE806 FOREIGN KEY (reported_by_id) REFERENCES worker (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11AFE65AF40 FOREIGN KEY (handled_by_id) REFERENCES worker (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE welfare_stock_change ADD CONSTRAINT FK_B565BE0E6B20BA36 FOREIGN KEY (worker_id) REFERENCES worker (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11A71CE806');
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11AFE65AF40');
        $this->addSql('ALTER TABLE welfare_stock_change DROP CONSTRAINT FK_B565BE0E6B20BA36');
        $this->addSql('DROP TABLE incident');
        $this->addSql('DROP TABLE welfare_current_stock');
        $this->addSql('DROP TABLE welfare_stock_change');
    }
}
