<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260215205009 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE score_ledger (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, reason VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, worker_id INT NOT NULL, task_instance_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_23A1E3626B20BA36 ON score_ledger (worker_id)');
        $this->addSql('CREATE INDEX IDX_23A1E3627C24DF2F ON score_ledger (task_instance_id)');
        $this->addSql('ALTER TABLE score_ledger ADD CONSTRAINT FK_23A1E3626B20BA36 FOREIGN KEY (worker_id) REFERENCES worker (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE score_ledger ADD CONSTRAINT FK_23A1E3627C24DF2F FOREIGN KEY (task_instance_id) REFERENCES task_instance (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE score_ledger DROP CONSTRAINT FK_23A1E3626B20BA36');
        $this->addSql('ALTER TABLE score_ledger DROP CONSTRAINT FK_23A1E3627C24DF2F');
        $this->addSql('DROP TABLE score_ledger');
    }
}
